/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import javax.swing.ImageIcon;

/**
 *
 * @author ANDRES FELIPE VIVEROS ALBAN - S3AN
 */
public class FrmCreador extends javax.swing.JInternalFrame {
    final int _Ancho = 32, Alto = 32;
    String[] ruta = {"/img/img_menu/Back_opt.png"};
    /** Creates new form FrmCreador */
    public FrmCreador() {
        
        
        initComponents();
        lblInfo.setText("INFORMACIÓN DEL CREADOR:");
        lblNombre.setText("Nombre: ");
        lblNom.setText("ANDRES FELIPE VIVEROS ALBAN");
        lblGrupo.setText("Grupo: ");
        lblGrup.setText("S3AN");
        lblCodigo.setText("Codigo: ");
        lblCodi.setText("1201037023");
        lblCorreoE.setText("Correo Electronico: ");
        lblCorreo.setText("Felipe9fdhdshj@gmail.com");
        lblTele.setText("Telefono: ");
        lblTel.setText("3114862498");
        lblFECEP.setText("FUNDACION CENTRO COLOMBIANO DE ESTUDIOS PROFESIONALES");
        lblPOO.setText("PROGRAMACION ORIENTADA A OBJETOS [POO]");
        ImageIcon foto_0 = new ImageIcon(getClass().getResource(ruta[0]));
        BtnVolver.setIcon(foto_0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoto = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        lblGrupo = new javax.swing.JLabel();
        lblGrup = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblCodi = new javax.swing.JLabel();
        lblCorreoE = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblTele = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblFECEP = new javax.swing.JLabel();
        lblPOO = new javax.swing.JLabel();

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_menu/Perfil-XD1_opt.png"))); // NOI18N
        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        lblInfo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblInfo.setText("jLabel2");

        lblNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNombre.setText("jLabel2");
        lblNombre.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblNom.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNom.setText("jLabel2");
        lblNom.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblGrupo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblGrupo.setText("jLabel2");
        lblGrupo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblGrup.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblGrup.setText("jLabel2");
        lblGrup.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCodigo.setText("jLabel2");
        lblCodigo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblCodi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCodi.setText("jLabel2");
        lblCodi.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblCorreoE.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCorreoE.setText("jLabel2");
        lblCorreoE.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblCorreo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCorreo.setText("jLabel2");
        lblCorreo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblTele.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTele.setText("jLabel2");
        lblTele.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblTel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTel.setText("jLabel2");
        lblTel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_menu/logo_opt.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblFECEP.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblFECEP.setText("jLabel2");
        lblFECEP.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblPOO.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPOO.setText("jLabel2");
        lblPOO.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPOO, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFECEP, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInfo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(252, 252, 252)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNom, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGrup, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodi, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTele, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTel, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblInfo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGrup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCodi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCorreoE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCorreo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTele)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTel)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblFECEP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPOO)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCodi;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreoE;
    private javax.swing.JLabel lblFECEP;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblGrup;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPOO;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblTele;
    // End of variables declaration//GEN-END:variables

}
