package Vista;

import Controlador.Login;
import Modelo.MySQL;
import static Vista.FrmSpaMascotas.Alto;
import static Vista.FrmSpaMascotas.Ancho;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author ANDRES FELIPE VIVEROS ALBAN - S3AN
 */
public class FrmLogin extends javax.swing.JFrame {

    public static String usuario = null; //variable publica que almacena el nombre de usuario para mostrar en los demas Frm
    Color color;
    private Timer tiempo; //variable privada de tipo timer para controlar la barra de progreso
    int cont = 0, Contador = 3; // contadores
    private ActionListener escuchar;
    MySQL db = new MySQL();

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        color = new Color(192, 192, 192);
        this.setTitle("Iniciar Sesion");//titulo del jframe
        Dimension _Screen = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(_Screen.width / 2, _Screen.height / 2);
        setLocationRelativeTo(null);

        //asignar icono para el JFRAME
        Image _Icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/Login.png"));
        setIconImage(_Icono);
        this.setResizable(false);
        initComponents();
        ImageIcon mimagen = new ImageIcon(getClass().getResource("/img/LOGIN12.png"));
        lblImagen.setIcon(mimagen);
        //asignar texto a los lbl, Btn etc
        lblTitulo.setText("BIENVENIDO AL SISTEMA DE LOGIN");
        lblUsuario.setText("ID de Usuario");
        lblPassword.setText("Contraseña");
        BtnLogin.setText("INICIAR SESION");
        txtPassword.setText("**********");
        txtPassword.setForeground(color);
        txtUsuario.setText("ID de Usuario");
        txtUsuario.setForeground(color);
        ImageIcon foto_1 = new ImageIcon(getClass().getResource("/img/Next.png"));
        ImageIcon mitad_1 = new ImageIcon(foto_1.getImage().getScaledInstance(Ancho, Alto, Image.SCALE_DEFAULT));
        BtnSeguir.setIcon(mitad_1);
        BtnSeguir.setToolTipText("Click para continuar al siguiente formulario");
        BtnSeguir.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        BtnLogin = new javax.swing.JButton();
        BtnSeguir = new javax.swing.JButton();
        Prgb = new javax.swing.JProgressBar();
        lblPor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblImagen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Foto De Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });

        BtnLogin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });

        BtnSeguir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeguirActionPerformed(evt);
            }
        });

        Prgb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lblPor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(BtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(BtnSeguir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(Prgb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnSeguir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPor, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Prgb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        db.RecognizeDATABASE("root", "", "Spa_MascotasAV");
        db.VerificarUsuarios();
        if (db.existe1 == 1) {
            db.RecognizeDATABASE("root", "", "");
        }
        if (db.existe1 == 0) {
            db.createTableRegistro("Usuarios");
        }
        Login Login=new Login();
        Login.RecognizeDATABASE("root", "", "Spa_MascotasAV");
        String ID = txtUsuario.getText();
        String Password = String.valueOf(txtPassword.getPassword());
        try {
            Login.login(ID, Password);
            if (Login.msm.equals("No Encontrado")) {
                Contador--;
                ImageIcon icono = new ImageIcon(getClass().getResource("/img/Error1.png"));
                ImageIcon mitad_0 = new ImageIcon(icono.getImage().getScaledInstance(Ancho, Alto, Image.SCALE_DEFAULT));
                JOptionPane.showMessageDialog(rootPane, "Error vuelva a intentar\nIntentos restantes: [" + Contador + "]", "ERROR", JOptionPane.PLAIN_MESSAGE, mitad_0);
                txtUsuario.setText("");
                txtPassword.setText("");
                txtUsuario.setEnabled(true);
                txtPassword.setEnabled(true);
                BtnSeguir.setEnabled(false);
                if (Contador == 0) {
                    Contador = 3;
                    txtUsuario.setEnabled(false);
                    txtPassword.setEnabled(false);
                    BtnLogin.setEnabled(false);
                    BtnSeguir.setEnabled(false);
                    lblImagen.setEnabled(false);
                    JOptionPane.showMessageDialog(rootPane, "Error vuelva a intentar mas tarde!!", "ERROR", JOptionPane.PLAIN_MESSAGE, mitad_0);
                }
            } else {
                if(ID.equals("1001")){
                ImageIcon mimagen = new ImageIcon(getClass().getResource("/img/VIVEROS-CECEP.jpg"));
                ImageIcon mitad_1 = new ImageIcon(mimagen.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
                lblImagen.setIcon(mitad_1);
                BtnSeguir.setEnabled(true);
                BtnLogin.setEnabled(false);
                txtUsuario.setEditable(false);
                txtPassword.setEditable(false);
                usuario = Login.rs.getString("ROL");
                }else{
                ImageIcon mimagen = new ImageIcon(getClass().getResource("/img/root.png"));
                ImageIcon mitad_1 = new ImageIcon(mimagen.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
                lblImagen.setIcon(mitad_1);
                BtnSeguir.setEnabled(true);
                BtnLogin.setEnabled(false);
                txtUsuario.setEditable(false);
                txtPassword.setEditable(false);
                usuario = Login.rs.getString("ROL");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if (txtPassword.getText().equals("")) {
            txtPassword.setText("**********");
            txtPassword.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        if (txtPassword.getText().equals("**********")) {
            txtPassword.setText("");
            txtPassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        if (txtUsuario.getText().equals("ID de Usuario")) {
            txtUsuario.setText("");
            txtUsuario.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        if (txtUsuario.getText().equals("")) {
            txtUsuario.setText("ID de Usuario");
            txtUsuario.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void BtnSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeguirActionPerformed
        ImageIcon icono = new ImageIcon(getClass().getResource("/img/Question.png"));
        ImageIcon mitad_0 = new ImageIcon(icono.getImage().getScaledInstance(Ancho, Alto, Image.SCALE_DEFAULT));
        int Q = JOptionPane.showConfirmDialog(rootPane, "Deseas ir al siguiente formulario?", "MENSAJE", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, mitad_0);
        if (Q == JOptionPane.YES_OPTION) {
            BtnSeguir.setEnabled(false);

            escuchar = new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent ae) {
                    cont = cont + 1;
                    Prgb.setValue(cont);
                    lblPor.setText(String.valueOf(cont) + " %");
                    lblPor.setHorizontalAlignment(0);

                    //***************************
                    if (Prgb.getValue() >= 0 && Prgb.getValue() <= 22) {
                        lblPor.setText("Verificando...");
                    }
                    //*******************
                    if (Prgb.getValue() >= 22 && Prgb.getValue() <= 36) {
                        lblPor.setText("Cargando Formulario Principal");
                    }
                    //*******************
                    if (Prgb.getValue() >= 36 && Prgb.getValue() <= 49) {
                        lblPor.setText("Accediendo por la sesion: " + usuario);
                    }
                    //*******************
                    if (Prgb.getValue() >= 49 && Prgb.getValue() <= 67) {
                        lblPor.setText("Verificando la conexion a la BD");
                    }
                    //*******************
                    if (Prgb.getValue() >= 67 && Prgb.getValue() <= 89) {
                        lblPor.setText("Analizando la integridad de los datos");
                    }
                    //*******************
                    if (Prgb.getValue() >= 89 && Prgb.getValue() <= 99) {
                        lblPor.setText("Todo esta listo :)");
                    }
                    //*******************
                    if (Prgb.getValue() == Prgb.getMaximum()) {
                        if (cont == 100) {
                            tiempo.stop();
                            FrmPrincipal Menu = new FrmPrincipal();
                            Menu.setVisible(true);
                            setVisible(false);

                        }
                    }
                }
            };

            tiempo = new Timer(110, escuchar);
            tiempo.start();//vuelve a iniciar el timer cuando finaliza la barra de progreso
            //*******************
        }
    }//GEN-LAST:event_BtnSeguirActionPerformed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtPassword.setEnabled(true);
            txtUsuario.setEnabled(false);
            txtUsuario.setFocusable(true);
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            db.RecognizeDATABASE("root", "", "Spa_MascotasAV");
            db.VerificarUsuarios();
            if (db.existe1 == 1) {
                db.RecognizeDATABASE("root", "", "");
            }
            if (db.existe1 == 0) {
                db.createTableRegistro("Usuarios");
            }
            Login Login = new Login();
            Login.RecognizeDATABASE("root", "", "Spa_MascotasAV");
            String ID = txtUsuario.getText();
            String Password = String.valueOf(txtPassword.getPassword());
            try {
                Login.login(ID, Password);
                if (Login.msm.equals("No Encontrado")) {
                    Contador--;
                    ImageIcon icono = new ImageIcon(getClass().getResource("/img/Error1.png"));
                    ImageIcon mitad_0 = new ImageIcon(icono.getImage().getScaledInstance(Ancho, Alto, Image.SCALE_DEFAULT));
                    JOptionPane.showMessageDialog(rootPane, "Error vuelva a intentar\nIntentos restantes: [" + Contador + "]", "ERROR", JOptionPane.PLAIN_MESSAGE, mitad_0);
                    txtUsuario.setText("");
                    txtPassword.setText("");
                    BtnSeguir.setEnabled(false);
                    txtUsuario.setEnabled(true);
                    txtPassword.setEnabled(true);
                    if (Contador == 0) {
                        Contador = 3;
                        txtUsuario.setEnabled(false);
                        txtPassword.setEnabled(false);
                        BtnLogin.setEnabled(false);
                        BtnSeguir.setEnabled(false);
                        lblImagen.setEnabled(false);
                        JOptionPane.showMessageDialog(rootPane, "Error vuelva a intentar mas tarde!!", "ERROR", JOptionPane.PLAIN_MESSAGE, mitad_0);
                    }
                } else {
                    if (ID.equals("1001")) {
                        ImageIcon mimagen = new ImageIcon(getClass().getResource("/img/VIVEROS-CECEP.jpg"));
                        ImageIcon mitad_1 = new ImageIcon(mimagen.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
                        lblImagen.setIcon(mitad_1);
                        BtnSeguir.setEnabled(true);
                        BtnLogin.setEnabled(false);
                        txtUsuario.setEditable(false);
                        txtPassword.setEditable(false);
                        txtPassword.setEnabled(false);
                        usuario = Login.rs.getString("ROL");
                    } else {
                        ImageIcon mimagen = new ImageIcon(getClass().getResource("/img/root.png"));
                        ImageIcon mitad_1 = new ImageIcon(mimagen.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
                        lblImagen.setIcon(mitad_1);
                        BtnSeguir.setEnabled(true);
                        BtnLogin.setEnabled(false);
                        txtUsuario.setEditable(false);
                        txtPassword.setEditable(false);
                        txtPassword.setEnabled(false);
                        usuario = Login.rs.getString("ROL");
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /**
                 * Cambiar apariencia al estilo del sistema*
                 */
//                try {
//                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
//                    Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
//                }
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JButton BtnSeguir;
    private javax.swing.JProgressBar Prgb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtPassword;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
